# Default values for upp-exports-rw-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/upp-exports-rw-s3
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 512Mi
